export enum CommonIconNames {
  HOME_ICON = "HOME_ICON",
  ORDERS_ICON = "ORDERS_ICON",
  PRODUCTS_ICON = "PRODUCTS_ICON",
  CATEGORIES_ICON = "CATEGORIES_ICON",
  STOCK_ICON = "STOCK_ICON",
  REPORTS_ICON = "REPORTS_ICON",
  MENU_ICON = "MENU_ICON",
  ARROW_RIGHT_ICON = "ARROW_RIGHT_ICON",
  BAR_CHART_ICON = "BAR_CHART_ICON",
  CALENDER_ICON = "CALENDER_ICON",
  CHECKBOX_ICON = "CHECKBOX_ICON",
  CHECK_MARK_ICON = "CHECK_MARK_ICON",
  CLOCK_ICON = "CLOCK_ICON",
  COG_ICON = "COG_ICON",
  DASHBOARD_ICON = "DASHBOARD_ICON",
  DATA_ICON = "DATA_ICON",
  DOWNLOAD_ICON = "DOWNLOAD_ICON",
  EDIT_ICON = "EDIT_ICON",
  FEEDBACK_ICON = "FEEDBACK_ICON",
  FILE_ICON = "FILE_ICON",
  FILTERS_ICON = "FILTERS_ICON",
  LANGUAGE_ICON = "LANGUAGE_ICON",
  LOGOUT_ICON = "LOGOUT_ICON",
  NOTIFICATION_ICON = "NOTIFICATION_ICON",
  OVERDUE_ICON = "OVERDUE_ICON",
  REPORT_ICON = "REPORT_ICON",
  RESOLUTION_ICON = "RESOLUTION_ICON",
  SEARCH_ICON = "SEARCH_ICON",
  SUSPEND_ICON = "SUSPEND_ICON",
  USER_ICON = "USER_ICON",
  USERS_ICON = "USERS_ICON",
  VIEW_ICON = "VIEW_ICON",
}

export interface IconType {
  width?: number;
  height?: number;
  className?: string;
  fill?: string;
}

export interface IconProps extends IconType {
  name: CommonIconNames;
}

export const IconColors = {
  WHITE_COLOR_ICON: "#FFFFFF",
  GRAY_COLOR_ICON: "#9CA3AF",
  PRIMARY_COLOR_ICON: "#059669",
  HAM_BURGER_ARROW: "#FFFFFF",
} as const;
